
#define GPIO_STARTSTOP GPIO_NUM_36
#define GPIO_PREVIOUS GPIO_NUM_39
#define GPIO_NEXT GPIO_NUM_34

#define GPIO_WIRE_SDA GPIO_NUM_21
#define GPIO_WIRE_SCL GPIO_NUM_22

#define GPIO_PN532_IRQ GPIO_NUM_32
#define GPIO_PN532_RST GPIO_NUM_33

#define GPIO_NEOPIXEL_DATA GPIO_NUM_25

#define GPIO_I2S_BCK GPIO_NUM_15
#define GPIO_I2S_WS GPIO_NUM_14
#define GPIO_I2S_DATA GPIO_NUM_12